export const headCells = [
  {
    id: "DEPT",
    numeric: true,
    disablePadding: false,
    label: "DEPT",
    width: "100%",
  },
  {
    id: "LOCATION",
    numeric: true,
    disablePadding: false,
    label: "LOCATION",
    width: "100%",
  },
  {
    id: "TRN_TYPE",
    numeric: true,
    disablePadding: false,
    label: "TRN_TYPE",
    width: "100%",
  },
  {
    id: "END_OF_PERIOD",
    numeric: true,
    disablePadding: false,
    label: "END OF PERIOD",
    width: "100%",
  },
  {
    id: "QTY",
    numeric: true,
    disablePadding: false,
    label: "QTY",
    width: "100%",
  },
  {
    id: "COST",
    numeric: false,
    disablePadding: false,
    label: "COST",
    width: "120px",
  },
  {
    id: "RETAIL",
    numeric: true,
    disablePadding: false,
    label: "RETAIL",
    width: "150px",
  },
  {
    id: "ROLLED_QTY",
    numeric: false,
    disablePadding: true,
    label: "ROLLED QTY",
    width: "100%",
  },
  {
    id: "ROLLED_COST",
    numeric: false,
    disablePadding: true,
    label: "ROLLED COST",
    width: "150px",
  },
  {
    id: "ROLLED_RETAIL",
    numeric: false,
    disablePadding: true,
    label: "ROLLED RETAIL",
    width: "100%",
  },
  {
    id: "QTY_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "QTY MATCHED",
    width: "150px",
  },
  {
    id: "COST_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "COST MATCHED",
    width: "100%",
  },
  {
    id: "RETAIL_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "RETAIL MATCHED",
    width: "150px",
  },
];
