export const headCells = [
  {
    id: "ITEM",
    numeric: true,
    disablePadding: false,
    label: "ITEM",
    width: "100%",
  },
  {
    id: "ITEM_DESC",
    numeric: true,
    disablePadding: false,
    label: "ITEM DESC",
    width: "150px",
  },
  {
    id: "DEPT",
    numeric: false,
    disablePadding: true,
    label: "DEPT",
    width: "100%",
  },
  {
    id: "CLASS",
    numeric: false,
    disablePadding: true,
    label: "CLASS",
    width: "100%",
  },
  {
    id: "SUBCLASS",
    numeric: false,
    disablePadding: true,
    label: "SUBCLASS",
    width: "100%",
  },
  {
    id: "REF_ITEM",
    numeric: true,
    disablePadding: false,
    label: "REF ITEM",
    width: "100%",
  },
  {
    id: "REF_ITEM_TYPE",
    numeric: true,
    disablePadding: false,
    label: "REF ITEM TYPE",
    width: "100%",
  },
  {
    id: "LOCATION_TYPE",
    numeric: true,
    disablePadding: false,
    label: "LOC TYPE",
    width: "100%",
  },
  {
    id: "LOCATION",
    numeric: true,
    disablePadding: false,
    label: "LOC",
    width: "100%",
  },
  {
    id: "LOCATION_NAME",
    numeric: true,
    disablePadding: false,
    label: "LOC NAME",
    width: "100%",
  },
  {
    id: "TRN_DATE",
    numeric: false,
    disablePadding: false,
    label: "TRN DATE",
    width: "100%",
  },
  {
    id: "TRN_TYPE",
    numeric: true,
    disablePadding: false,
    label: "TRN TYPE",
    width: "100%",
  },
  {
    id: "QTY",
    numeric: false,
    disablePadding: true,
    label: "QTY",
    width: "100%",
  },
  {
    id: "PACK_QTY",
    numeric: false,
    disablePadding: true,
    label: "PACK QTY",
    width: "100%",
  },
  {
    id: "PACK_COST",
    numeric: true,
    disablePadding: false,
    label: "PACK COST",
    width: "100%",
  },
  {
    id: "PACK_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "PACK RETAIL",
    width: "100%",
  },
  {
    id: "UNIT_COST",
    numeric: true,
    disablePadding: false,
    label: "UNIT COST",
    width: "100%",
  },
  {
    id: "UNIT_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "UNIT RETAIL",
    width: "100%",
  },
  {
    id: "TOTAL_COST",
    numeric: true,
    disablePadding: false,
    label: "TOTAL COST",
    width: "100%",
  },
  {
    id: "TOTAL_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "TOTAL RETAIL",
    width: "100%",
  },
  {
    id: "REF_NO1",
    numeric: false,
    disablePadding: true,
    label: "REF NO1",
    width: "100%",
  },
  {
    id: "REF_NO2",
    numeric: true,
    disablePadding: false,
    label: "REF NO2",
    width: "100%",
  },
  {
    id: "REF_NO3",
    numeric: true,
    disablePadding: false,
    label: "REF NO3",
    width: "100%",
  },
  {
    id: "REF_NO4",
    numeric: true,
    disablePadding: false,
    label: "REF NO4",
    width: "100%",
  },
  {
    id: "CURRENCY",
    numeric: true,
    disablePadding: false,
    label: "CURRENCY",
    width: "100%",
  },
  {
    id: "CREATE_ID",
    numeric: false,
    disablePadding: false,
    label: "CREATE ID",
    width: "100%",
  },
  {
    id: "CREATE_DATETIME",
    numeric: false,
    disablePadding: false,
    label: "CREATE DATETIME",
    width: "120px",
  },
  {
    id: "REV_NO",
    numeric: false,
    disablePadding: false,
    label: "REV NO",
    width: "100%",
  },
  {
    id: "REV_TRN_NO",
    numeric: false,
    disablePadding: false,
    label: "REV TRN NO",
    width: "100%",
  },
  {
    id: "ERR_MSG",
    numeric: false,
    disablePadding: false,
    label: "ERR MSG",
    width: "100px",
  },
  {
    id: "ERR_SEQ_NO",
    numeric: false,
    disablePadding: false,
    label: "ERR SEQ NO",
    width: "100%",
  },
  {
    id: "TRAN_SEQ_NO",
    numeric: false,
    disablePadding: true,
    label: "TRAN SEQ NO",
    width: "100%",
  },
];
