export const headCells = [
  {
    id: "ITEM",
    numeric: true,
    disablePadding: false,
    label: "ITEM",
    width: "100%",
  },
  {
    id: "LOC_TYPE",
    numeric: true,
    disablePadding: false,
    label: "LOC TYPE",
    width: "90px",
  },
  {
    id: "LOC",
    numeric: true,
    disablePadding: false,
    label: "LOC",
    width: "100%",
  },
  {
    id: "TRN_DATE",
    numeric: false,
    disablePadding: false,
    label: "TRN DATE",
    width: "90px",
  },
  {
    id: "TRN_TYPE",
    numeric: true,
    disablePadding: false,
    label: "TRN TYPE",
    width: "200px",
  },
  {
    id: "QTY",
    numeric: false,
    disablePadding: false,
    label: "QTY",
    width: "100%",
  },
  {
    id: "UNIT_COST",
    numeric: true,
    disablePadding: false,
    label: "UNIT COST",
    width: "100px",
  },
  {
    id: "UNIT_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "UNIT RETAIL",
    width: "110px",
  },
  {
    id: "REF_NO1",
    numeric: false,
    disablePadding: false,
    label: "REF NO1",
    width: "90px",
  },
  {
    id: "REF_NO2",
    numeric: true,
    disablePadding: false,
    label: "REF NO2",
    width: "90px",
  },
  {
    id: "REF_NO3",
    numeric: true,
    disablePadding: false,
    label: "REF NO3",
    width: "90px",
  },
  {
    id: "REF_NO4",
    numeric: true,
    disablePadding: false,
    label: "REF NO4",
    width: "90px",
  },
  {
    id: "CREATE_DATETIME",
    numeric: false,
    disablePadding: false,
    label: "CREATE DATETIME",
    width: "150px",
  },
  {
    id: "CREATE_ID",
    numeric: false,
    disablePadding: false,
    label: "CREATE ID",
    width: "100px",
  },
];
