export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING="RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";


