export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING="RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";
export const GET_CLASSDATA_REQUEST = "GET_CLASSDATA_REQUEST";
export const GET_CLASSDATA_SUCCESS = "GET_CLASSDATA_SUCCESS";
export const GET_CLASSDATA_ERROR = "GET_CLASSDATA_ERROR";
export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_ERROR = "GET_LOCATIONDATA_ERROR";
export const GET_SYSTEMCONFIG_REQUEST = "GET_SYSTEMCONFIG_REQUEST";
export const GET_SYSTEMCONFIG_SUCCESS = "GET_SYSTEMCONFIG_SUCCESS";
export const GET_SYSTEMCONFIG_ERROR = "GET_SYSTEMCONFIG_ERROR";
export const POST_SYSTEMCONFIG_REQUEST = "POST_SYSTEMCONFIG_REQUEST";
export const POST_SYSTEMCONFIG_SUCCESS = "POST_SYSTEMCONFIG_SUCCESS";
export const POST_SYSTEMCONFIG_ERROR = "POST_SYSTEMCONFIG_ERROR";


