export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING="RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";
export const GET_CLASSDATA_REQUEST = "GET_CLASSDATA_REQUEST";
export const GET_CLASSDATA_SUCCESS = "GET_CLASSDATA_SUCCESS";
export const GET_CLASSDATA_ERROR = "GET_CLASSDATA_ERROR";
export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_ERROR = "GET_LOCATIONDATA_ERROR";
export const GET_SYSTEMCONFIG_REQUEST = "GET_SYSTEMCONFIG_REQUEST";
export const GET_SYSTEMCONFIG_SUCCESS = "GET_SYSTEMCONFIG_SUCCESS";
export const GET_SYSTEMCONFIG_ERROR = "GET_SYSTEMCONFIG_ERROR";
export const POST_SYSTEMCONFIG_REQUEST = "POST_SYSTEMCONFIG_REQUEST";
export const POST_SYSTEMCONFIG_SUCCESS = "POST_SYSTEMCONFIG_SUCCESS";
export const POST_SYSTEMCONFIG_ERROR = "POST_SYSTEMCONFIG_ERROR";
export const GET_DAILYCOUNT_REQUEST = "GET_DAILYCOUNT_REQUEST";
export const GET_DAILYCOUNT_SUCCESS = "GET_DAILYCOUNT_SUCCESS";
export const GET_DAILYCOUNT_ERROR = "GET_DAILYCOUNT_ERROR";
export const GET_STAGECOUNT_REQUEST = "GET_STAGECOUNT_REQUEST";
export const GET_STAGECOUNT_SUCCESS = "GET_STAGECOUNT_SUCCESS";
export const GET_STAGECOUNT_ERROR = "GET_STAGECOUNT_ERROR";
export const GET_ERRORCOUNT_REQUEST = "GET_ERRORCOUNT_REQUEST";
export const GET_ERRORCOUNT_SUCCESS = "GET_ERRORCOUNT_SUCCESS";
export const GET_ERRORCOUNT_ERROR = "GET_ERRORCOUNT_ERROR";
export const GET_DAILY_SKU_ROLLUPDATA_REQUEST = "GET_DAILY_SKU_ROLLUPDATA_REQUEST";
export const GET_DAILY_SKU_ROLLUPDATA_SUCCESS = "GET_CLASSDATA_SUCCESS";
export const GET_DAILY_SKU_ROLLUPDATA_ERROR = "GET_DAILY_SKU_ROLLUPDATA_ERROR";
export const GET_DEPTRECDATA_REQUEST = "GET_DEPTRECDATA_REQUEST";
export const GET_DEPTRECDATA_SUCCESS = "GET_DEPTRECDATA_SUCCESS";
export const GET_DEPTRECDATA_ERROR = "GET_DEPTRECDATA_ERROR";
export const GET_LOCATIONRECDATA_REQUEST = "GET_LOCATIONRECDATA_REQUEST";
export const GET_LOCATIONRECDATA_SUCCESS = "GET_LOCATIONRECDATA_SUCCESS";
export const GET_LOCATIONRECDATA_ERROR = "GET_LOCATIONRECDATA_ERROR";
export const GET_INQUIRYDATA_REQUEST = "GET_INQUIRYDATA_REQUEST";
export const GET_INQUIRYDATA_SUCCESS = "GET_INQUIRYDATA_SUCCESS";
export const GET_INQUIRYDATA_ERROR = "GET_INQUIRYDATA_ERROR";




