export const headCells = [
  {
    id: "TRN_TYPE",
    numeric: true,
    disablePadding: false,
    label: "TRN TYPE",
    width: "150px",
  },
  {
    id: "STCK_LDGR_APPL",
    numeric: false,
    disablePadding: false,
    label: "STCK LDGR APPL",
    width: "140px",
  },
  {
    id: "SOH_IMPACT",
    numeric: true,
    disablePadding: false,
    label: "SOH IMPACT",
    width: "120px",
  },
  {
    id: "COST_USED",
    numeric: true,
    disablePadding: false,
    label: "COST USED",
    width: "120px",
  },
  {
    id: "PERIOD_INVT_TRAN",
    numeric: false,
    disablePadding: true,
    label: "PERIOD INVT TRAN",
    width: "150px",
  },
  {
    id: "INJECT_PERIOD",
    numeric: false,
    disablePadding: true,
    label: "INJECT PERIOD",
    width: "130px",
  },
  {
    id: "OVERRIDE_ACCUMULATE",
    numeric: false,
    disablePadding: true,
    label: "OVERRIDE ACCUMULATE",
    width: "190px",
  },
  {
    id: "HIER_LEVEL",
    numeric: false,
    disablePadding: true,
    label: "HIER LEVEL",
    width: "100px",
  },
  {
    id: "FIN_APPL",
    numeric: false,
    disablePadding: true,
    label: "FIN APPL",
    width: "100px",
  },
  {
    id: "ACCT_REFERENCE",
    numeric: false,
    disablePadding: true,
    label: "ACCT REFERENCE",
    width: "150px",
  }
];
